ProjectBundle:
    resource: "@ProjectTemplateBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_user_bundle:
    resource: "@ProjectUserBundle/Resources/config/routing.yml"