<?php

namespace Project\TemplateBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Project\UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
}
